image: k33g/capsule:0.0.1

tasks:
  - name: initialize
    before: |
      CAPSULE_VERSION="0.1.9"
      echo "💊 Installing the capsule launcher..."
      wget https://github.com/bots-garden/capsule/releases/download/${CAPSULE_VERSION}/capsule-${CAPSULE_VERSION}-linux-amd64.tar.gz
      sudo tar -zxf capsule-${CAPSULE_VERSION}-linux-amd64.tar.gz --directory /usr/local/bin
      rm capsule-${CAPSULE_VERSION}-linux-amd64.tar.gz

      echo "💊 Installing the capsule registry..."
      wget https://github.com/bots-garden/capsule/releases/download/${CAPSULE_VERSION}/capsule-registry-${CAPSULE_VERSION}-linux-amd64.tar.gz
      sudo tar -zxf capsule-registry-${CAPSULE_VERSION}-linux-amd64.tar.gz --directory /usr/local/bin
      rm capsule-registry-${CAPSULE_VERSION}-linux-amd64.tar.gz

      echo "💊 Installing the capsule reverse-proxy..."
      wget https://github.com/bots-garden/capsule/releases/download/${CAPSULE_VERSION}/capsule-reverse-proxy-${CAPSULE_VERSION}-linux-amd64.tar.gz
      sudo tar -zxf capsule-reverse-proxy-${CAPSULE_VERSION}-linux-amd64.tar.gz --directory /usr/local/bin
      rm capsule-reverse-proxy-${CAPSULE_VERSION}-linux-amd64.tar.gz

      echo "💊 Installing the capsule worker..."
      wget https://github.com/bots-garden/capsule/releases/download/${CAPSULE_VERSION}/capsule-worker-${CAPSULE_VERSION}-linux-amd64.tar.gz
      sudo tar -zxf capsule-worker-${CAPSULE_VERSION}-linux-amd64.tar.gz --directory /usr/local/bin
      rm capsule-worker-${CAPSULE_VERSION}-linux-amd64.tar.gz

      echo "💊 Installing capsule cli..."
      wget https://github.com/bots-garden/capsule/releases/download/${CAPSULE_VERSION}/caps-${CAPSULE_VERSION}-linux-amd64.tar.gz
      sudo tar -zxf caps-${CAPSULE_VERSION}-linux-amd64.tar.gz --directory /usr/local/bin
      rm caps-${CAPSULE_VERSION}-linux-amd64.tar.gz
    init: |
      echo "🚀 ..."


ports:
  - port: 3000-25000
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - aaron-bond.better-comments
